name: projet_b3
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.2.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_launcher_icons: ^0.7.4
  flutter_map: ^0.8.2
  latlong: ^0.6.1
  intl: 0.15.7
  http: ^0.12.1
  google_maps_flutter: ^0.5.28+1
  permission_handler: ^5.0.0+hotfix.6
  geolocator: ^5.3.1
  query_params: ^0.6.1
  crypto: ^2.1.4
  shared_preferences: ^0.5.7+3

dev_dependencies:
  flutter_test:
    sdk: flutter

# Used to change launcher icon
flutter_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/launcher_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/add.png
    - assets/cb.png
    - assets/circle.png
    - assets/circular_arrow.png
    - assets/download.png
    - assets/edit.png
    - assets/facebook.png
    - assets/favorite_empty.png
    - assets/favorite_full.png
    - assets/filters.png
    - assets/google.png
    - assets/home_empty.png
    - assets/home_full.png
    - assets/instagram.png
    - assets/location_pin.png
    - assets/logging_in.gif
    - assets/logo.png
    - assets/money.png
    - assets/orders_full.png
    - assets/orders_empty.png
    - assets/paypal.png
    - assets/recenter.png
    - assets/remove.png
    - assets/search.png
    - assets/settings_empty.png
    - assets/settings_full.png
    - assets/trash.png
    - assets/valid.png
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
